<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.noria</groupId>
    <artifactId>cdafhirlib</artifactId>
    <version>1.0.${v}-SNAPSHOT</version>


    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <hapi.version>5.6.0</hapi.version>
    </properties>

    <dependencies>

        <!-- Obtained from https://github.com/mdht/mdht-models/releases/tag/v20220126 -->
        <!-- MDHT 3rd Party Dependencies that have been added to local mvn repo -->
        <dependency>
            <groupId>lpg.runtime</groupId>
            <artifactId>java</artifactId>
            <version>2.0.17</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf.ecore</groupId>
            <artifactId>xmi</artifactId>
            <version>2.13.0</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf</groupId>
            <artifactId>ecore</artifactId>
            <version>2.13.0</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf</groupId>
            <artifactId>common</artifactId>
            <version>2.13.0</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse</groupId>
            <artifactId>ocl</artifactId>
            <version>3.6.200</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.ocl</groupId>
            <artifactId>common</artifactId>
            <version>1.4.200</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.ocl</groupId>
            <artifactId>ecore</artifactId>
            <version>3.6.200</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.uml2</groupId>
            <artifactId>types</artifactId>
            <version>2.0.0</version>
        </dependency>
        <!-- MDHT Core Dependencies -->
        <dependency>
            <groupId>org.eclipse.mdht.emf</groupId>
            <artifactId>runtime</artifactId>
            <version>3.0.0</version>
        </dependency>
        <!-- MDHT CDA Dependencies -->
        <dependency>
            <groupId>org.eclipse.mdht.uml.hl7</groupId>
            <artifactId>vocab</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.mdht.uml.hl7</groupId>
            <artifactId>datatypes</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.mdht.uml.hl7</groupId>
            <artifactId>rim</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.mdht.uml</groupId>
            <artifactId>cda</artifactId>
            <version>3.0.0</version>
        </dependency>
        <!-- MDHT CDA Implementation Guide Dependencies -->
        <dependency>
            <groupId>org.openhealthtools.mdht.uml.cda</groupId>
            <artifactId>consol2</artifactId>
            <version>3.0.0</version>
        </dependency>

        <!-- Other Dependencies-->


        <dependency>
            <groupId>ca.uhn.hapi.fhir</groupId>
            <artifactId>hapi-fhir-structures-r4</artifactId>
            <version>${hapi.version}</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/ca.uhn.hapi.fhir/hapi-fhir-validation-resources-r4 -->
        <dependency>
            <groupId>ca.uhn.hapi.fhir</groupId>
            <artifactId>hapi-fhir-validation-resources-r4</artifactId>
            <version>${hapi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.22</version>
            <scope>provided</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.apache.commons/commons-collections4 -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-collections4</artifactId>
            <version>4.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.14.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.14.1</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.8.1</version>
            <scope>test</scope>
        </dependency>

    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>
           <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <finalName>${artifactId}-${version}</finalName>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <appendAssemblyId>false</appendAssemblyId>
                </configuration>

                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>

            </plugin>

        </plugins>
    </build>
    <packaging>jar</packaging>
    <name>CDA to FHIR and Back Transformer Library</name>


</project>